### ISSUE TITLE
Links and search in navbar don't work when using dark mode

### ISSUE THREAD

**Issue by saewitz** [planetterp/PlanetTerp#47]

**Comment by tybug** [comment]
due to the z-index of our star background fill. Going to be a tricky one as we want it to be above `.fixed-top` (z-index 1030) but below `.nav-item` (z-index 1 **in a separate stacking context** due to the flexbox). I don't see any easy way to achieve this due to the difference stacking contexts.

**Comment by saewitz** [comment]
did it work before web.py? if so what about the change broke it?

**Comment by kandasamyc** [comment]
Ok, I've got a bit of sketchy fix for this: I changed the canvas z-index to 1000, and then set the color of the navbar to transparent. This works perfectly on desktop, although on mobile, the dropdown menu now has a completely black background since the the canvas doesn't extend there. 
![image](https://user-images.githubusercontent.com/35542397/222876405-95e993f6-60ee-4246-a2e5-7a0920613c30.png)
![image](https://user-images.githubusercontent.com/35542397/222876448-5d02fff7-c091-4eef-a600-81614f530b71.png)

**Comment by tybug** [comment]
I think we can live with the dropdown not having stars in it. I imagine that would be pretty tricky to get to work correctly.

Will have to see the code but this approach seems ok to me, as long as it doesn't require any changes to the normal (lightmode) css. I'm ok with sketchy css for the rarely-used darkmode, but not for the standard styling.

**Comment by kandasamyc** [comment]
I'll make the PR now, really the only sketchy part has to do with some manual adjust of the dropdown using negative paddings to account for the now transparent parent navbar padding.
